builds:
- main: ./cmd/tlsaudit/tlsaudit.go
  env:
    - CGO_ENABLED=1
  goos: 
    - darwin
  goarch:
    - amd64
archives:
    - id: darwin
      replacements:
        darwin: Darwin
        amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
before:
   hooks:
   - go mod download
brews:
  -
    github:
      owner: adedayo
      name: homebrew-tap
    homepage: "https://github.com/adedayo/tlsaudit"
    description: "tlsaudit is a utility for auditing TLS (including SSL and STARTTLS) security settings. You can use it to enumerate protocols, ciphers and curves supported by an open TCP port."
