language: go
go:
- 1.11.x
gobuild_args: -a -tags pcap -ldflags '-w -extldflags "-static"'
before_install:
- sudo apt-get install git cmake flex bison
- export PCAP_VERSION=1.9.0
- wget https://github.com/the-tcpdump-group/libpcap/archive/libpcap-$PCAP_VERSION.tar.gz
- mkdir libpcap
- tar xzf libpcap-$PCAP_VERSION.tar.gz -C libpcap --strip-components 1
- pushd libpcap
- cmake . && make && sudo make install
- popd
- go get ./...
script:
- make
deploy:
  provider: releases
  api_key:
    secure: ViQza1CDUDww9KLMJuGYu3P9XQVLZE5f039XUEWTzeBOJ9UUKNKvE9h3n+3YlogfXkjyTgscPQ17nO6qGm9LQwYn40LM6XaXz25TzkJOZBg8v9PTq3wi3JJTpzQl4wjT0xYo5Awi2R1NYWk0ZLAiQuFhy3wCf8F5NYcrb4oIUDwwMDmbluZhWc4Ui2yQsU06Jx4dtH4Nb2h5r7kAHNk/RkQ/2/MlC+RRitMOnaCAkjgTuPKtbUG7GiI/Yzktjo1BPYVzJPoAVtV4rSPs/5fizGkLizo/Qo6RAKk4XmeeuoYEXlFM7zko0ayPOiDrYb/aPKfHO+vzPmwspBp6eQQSWsl/kOFI+CTQ/KwjL+j1KnWcNIuMstbPm+kyJTuM21lZ7IPr7HUhNalW90IW3DB8TF5F6ercvnSALS1aN8ABsTIsKvD8wc04NN/2NLNv7PuOYHy3WFSXnd2zmUad3cRXwmheIMwI5+y+c3BQLizFUUY/P1Puxm5OdjPgom8U67r+AHUJxiTCLtutDcfm4JvKv7hcWAQA5v3+ZZJH6XZbiZSw0FzOXHlk53PHQiApqhwjp/4gTvDO2NXDfRTt+J7oKV0p/YNZD2CvG6Ka1mBvcff8gEFZy+D3wETAnq+L7xdGympJDa9ObfMGFkNNX9FXYrygmQtMaVCk550tVpVEl50=
  file_glob: true
  file: tlsaudit*.tar.gz
  skip_cleanup: true
  on:
    tags: true